"""empty message

Revision ID: e9ce5332c829
Revises: 
Create Date: 2021-11-22 22:56:17.255331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ce5332c829'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_time', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('ticket_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('hosts',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('association',
    sa.Column('announcementsid_', sa.Integer(), nullable=True),
    sa.Column('hostsid_', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['announcementsid_'], ['announcements.id_'], ),
    sa.ForeignKeyConstraint(['hostsid_'], ['hosts.id_'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('hosts')
    op.drop_table('announcements')
    # ### end Alembic commands ###
